---
  - name: Install Java Default Package [Ubuntu]
    hosts: ubuntu

    tasks:
     - name: Installing [ Java ]
       apt:
         name: default-jre
         state: latest
         update_cache: yes

  - name: Installing Java Default Package [Centos]
    hosts: centos

    tasks:
     - name: Installing [Java]
       yum:
         name: java-1.8.0-openjdk
         state: latest
         update_cache: yes

  - name: Installing [ubuntu] & [centos] using pip
    hosts: all

    tasks:
     - name: Installing [boto,ansible, and openstack]
       pip:
         name:
            - boto
            - ansible
            - python-openstackclient
